<?php

return [

    'spcambo' => [
        'api_key_lookup_secret' => env('SP_CAMBO_API_KEY_LOOKUP_SECRET'),
        'management_key_lookup_secret' => env('SP_CAMBO_MANAGEMENT_KEY_LOOKUP_SECRET'),
        'redeem_code_lookup_secret' => env('SP_CAMBO_REDEEM_CODE_LOOKUP_SECRET'),
        'gateway_secret' => env('SP_CAMBO_INTERNAL_GATEWAY_SECRET'),
        'allow_private_provider_origins' => filter_var(env('SP_CAMBO_ALLOW_PRIVATE_PROVIDER_ORIGINS', false), FILTER_VALIDATE_BOOL),
        'gateway_base_url' => env('SP_CAMBO_GATEWAY_BASE_URL', 'http://127.0.0.1:3010'),
        'public_gateway_base_url' => env('SP_CAMBO_PUBLIC_GATEWAY_BASE_URL', env('SP_CAMBO_GATEWAY_BASE_URL', 'http://127.0.0.1:3010')),
        'playground_daily_token_quota' => (int) env('SP_CAMBO_PLAYGROUND_DAILY_TOKEN_QUOTA', 20000),
        'playground_timeout_seconds' => (int) env('SP_CAMBO_PLAYGROUND_TIMEOUT_SECONDS', 90),
        'package_stock_reservation_ttl_seconds' => max(300, (int) env('SP_CAMBO_PACKAGE_STOCK_RESERVATION_TTL_SECONDS', 900)),

        // Explicit database-driven sell catalog seed. These two values identify
        // the private OmniRoute connection only. Runtime model selection NEVER
        // comes from a global ANTHROPIC_MODEL setting: each public alias resolves
        // through ModelAlias -> AiModel.internal_model_id in the database. The
        // exact private OmniRoute IDs are seeded as "OpenAI Codex" and
        // "Gemini Google AI Studio" and may also be managed in Admin.
        'sell_catalog_base_url' => env('ANTHROPIC_BASE_URL'),
        'sell_catalog_token' => env('ANTHROPIC_AUTH_TOKEN'),
    ],

    'telegram' => [
        // Fix19: ONE customer-facing Telegram Store Bot only. The website never
        // emits Telegram order/admin alerts. Legacy TELEGRAM_BOT_* names remain
        // accepted so an existing install can upgrade without rotating its bot.
        'storefront_bot_token' => env('TELEGRAM_STOREFRONT_BOT_TOKEN', env('TELEGRAM_BOT_TOKEN')),
        'storefront_webhook_secret' => env('TELEGRAM_STOREFRONT_WEBHOOK_SECRET', env('TELEGRAM_WEBHOOK_SECRET')),
        'storefront_link_secret' => env('TELEGRAM_STOREFRONT_LINK_SECRET', env('TELEGRAM_LINK_SECRET')),
        'storefront_bot_username' => env('TELEGRAM_STOREFRONT_BOT_USERNAME', env('TELEGRAM_BOT_USERNAME')),
        'bot_token' => env('TELEGRAM_STOREFRONT_BOT_TOKEN', env('TELEGRAM_BOT_TOKEN')),
        'webhook_secret' => env('TELEGRAM_STOREFRONT_WEBHOOK_SECRET', env('TELEGRAM_WEBHOOK_SECRET')),
        'link_secret' => env('TELEGRAM_STOREFRONT_LINK_SECRET', env('TELEGRAM_LINK_SECRET')),
        'bot_username' => env('TELEGRAM_STOREFRONT_BOT_USERNAME', env('TELEGRAM_BOT_USERNAME')),
        'support_url' => env('TELEGRAM_STOREFRONT_SUPPORT_URL'),
        'timeout_seconds' => (int) env('TELEGRAM_HTTP_TIMEOUT_SECONDS', 15),
        'delivery_lease_seconds' => max(30, (int) env('TELEGRAM_DELIVERY_LEASE_SECONDS', 120)),
        'announcement_lease_seconds' => max(30, (int) env('TELEGRAM_ANNOUNCEMENT_LEASE_SECONDS', 120)),
        'announcement_max_attempts' => max(1, (int) env('TELEGRAM_ANNOUNCEMENT_MAX_ATTEMPTS', 8)),

        // Subscriber activity generated by Telegram Store events only. Website
        // checkout never reaches this pipeline.
        'purchase_activity_enabled' => filter_var(env('TELEGRAM_STOREFRONT_PURCHASE_ACTIVITY_ENABLED', true), FILTER_VALIDATE_BOOL),
        'purchase_activity_min_delay_seconds' => max(0, (int) env('TELEGRAM_STOREFRONT_PURCHASE_ACTIVITY_MIN_DELAY_SECONDS', 5)),
        'purchase_activity_max_per_hour' => max(1, (int) env('TELEGRAM_STOREFRONT_PURCHASE_ACTIVITY_MAX_PER_HOUR', 30)),
        'public_purchase_template_en' => env('TELEGRAM_STOREFRONT_PURCHASE_TEMPLATE_EN'),
        'public_purchase_template_km' => env('TELEGRAM_STOREFRONT_PURCHASE_TEMPLATE_KM'),

        // Hard-disabled compatibility keys from Fix17. They intentionally do not
        // read environment flags: website/admin/public-channel Telegram alerts are
        // no longer part of SP Cambo's architecture.
        'website_alert_bot_token' => null,
        'website_purchase_alert_chat_ids' => [],
        'customer_order_alerts_enabled' => false,
        'purchase_feed_enabled' => false,
        'purchase_feed_subscribers_enabled' => false,
        'purchase_feed_chat_ids' => [],
    ],
    'bakong' => [
        'base_url' => env('BAKONG_BASE_URL', 'https://api-bakong.nbc.gov.kh'),
        'token' => env('BAKONG_TOKEN'),
        'account_id' => env('BAKONG_ACCOUNT_ID'),
        'merchant_name' => env('BAKONG_MERCHANT_NAME'),
        'merchant_city' => env('BAKONG_MERCHANT_CITY', 'Phnom Penh'),
        'currency' => env('BAKONG_CURRENCY', 'USD'),
        'attempt_ttl_seconds' => (int) env('BAKONG_PAYMENT_ATTEMPT_TTL_SECONDS', 300),
        'reconcile_interval_seconds' => max(15, (int) env('BAKONG_RECONCILE_INTERVAL_SECONDS', 60)),
        'customer_auto_check_interval_seconds' => max(15, (int) env('BAKONG_CUSTOMER_AUTO_CHECK_INTERVAL_SECONDS', 15)),
        'reconcile_expired_grace_seconds' => max(0, (int) env('BAKONG_RECONCILE_EXPIRED_GRACE_SECONDS', 900)),
        'verification_lease_seconds' => max(30, (int) env('BAKONG_VERIFICATION_LEASE_SECONDS', 90)),
        'khqr_generator_url' => env('BAKONG_KHQR_GENERATOR_URL'),
        'khqr_generator_secret' => env('BAKONG_KHQR_GENERATOR_SECRET'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Resend, Postmark, AWS, and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect' => env('GOOGLE_REDIRECT_URI'),
    ],

];
